spring:
  application:
    name: zuul-server
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@eureka/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 8893
zuul:
  routes:
    api-a:
      path: /api-demo/**
      service-id: demo-server
    api-b:
      path: /api-demo2/**
      service-id: demo2-server
    api-b:
          path: /eureka/**
          service-id: register-center