spring:
  application:
    name: zuul-server
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@aitieta.com:8888/eureka/,http://root:123456@aitieta.com:8887/eureka/
    eureka-server-read-timeout-seconds: 10000
    eureka-service-url-poll-interval-seconds: 10
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
    instance-id: ${eureka.instance.ip-address}:${server.port}
    ip-address: aitieta.com
server:
  port: 8893
zuul:
  routes:
    api-a:
      path: /api-demo/**
      service-id: demo-server
    api-b:
      path: /api-demo2/**
      service-id: demo2-server
#  host:
#    connect-timeout-millis: 10000
#    socket-timeout-millis: 10000
ribbon:
  ReadTimeout:  10000
  ConnectTimeout:  10000
#  eureka:
#    enabled: true
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 40000
#        timeout:
#          enabled: true